server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=LEGACY
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true 
  sql:
    init:
      mode: always                         
  h2:
    console:
      enabled: true
      path: /h2-console

security:
  jwt:
    secret: "mysupersecretkeymysupersecretkey"
    expiration-minutes: 15

crypto:
  default-key-base64: "MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE="
  default-iv-base64: "MDEyMzQ1Njc4OTAxMjM0NQ=="
